### ISSUE TITLE
Rework display requests queueing

### ISSUE THREAD

**Issue by nadako** [vshaxe/haxe-languageserver#12]
(originally reported by @kevinresol vshaxe/vshaxe#12)

Right now we simply dump all incoming requests to the haxe's stdin, so if project is macro-heavy and requests take significant amount of time, they queue up resulting in very poor performance and CPU usage.

What we should do is queue up requests in the language server and only send them to haxe if the previous request has been processed. That way we can do cancellation processing and remove cancelled requests from the queue so they never sent to haxe.

**Comment by nadako** [comment]
@kevinresol I implemented this, could you test it in your setup before I release it? (installing the plugin from github using [these instructions](https://github.com/vshaxe/vshaxe#hacking))

**Comment by kevinresol** [comment]
I _think_ it is working. Apparently it no longer eats up my CPU for minutes after I stopped typing.

**Comment by nadako** [comment]
Nice, let's ship it :)
