### ISSUE TITLE
Generate imports

### ISSUE THREAD

**Issue by nadako** [vshaxe/haxe-languageserver#13]
This is a related, but different feature than discussed in vshaxe/vshaxe#2. It should be much easier to actually implement.

[haxe-sublime-bundle](https://github.com/clemos/haxe-sublime-bundle) has a neat feature that allows you to type a fully qualified type path, then press a key combo and have an import statement generated at the top of the file:
![](https://github.com/r3a1ay/helper/raw/master/img/haxe/auto_import.gif)
It does simple text processing trying to guess what to actually import, it supports simple module and type imports and can have a number of false positives, but it's still very useful.

It would be cool to have the same in vshaxe, but to get it right, I'm afraid we need some compiler support. In Haxe we might want to:
- import a whole module 
- import a type from a module
- import a static from a class
- import everything from a package or all statics from a class (though these use cases are more rare)

To determine what options do we have and what to actually import (e.g. "is this a main module type? a type within a module? a static field of a class?") we need a display query that tries to resolve a given dot-path and gives us info about it.

**Comment by nadako** [comment]
I just did a refactoring that separates code actions from diagnostics so that we can have different code actions providers. One of those providers could be this feature!

**Comment by Simn** [comment]
Can this be closed or is there something left to do?

**Comment by nadako** [comment]
I still haven't looked into what's currently implemented :)

**Comment by Gama11** [comment]
It's missing these two I guess:

- import a static from a class
- import everything from a package or all statics from a class (though these use cases are more rare)

**Comment by ncannasse** [comment]
Can we have this disable by default? :)

**Comment by Gama11** [comment]
@ncannasse Considering that due to being a code action, this is already behind a shortcut, I'm not sure what you'd want to disble here.

**Comment by ncannasse** [comment]
@Gama11 most of the IDE do some automatic replacements without code action for this feature

**Comment by Gama11** [comment]
Ah, you mean auto-import. There's another issue for that, and it's not implemented yet: https://github.com/vshaxe/vshaxe/issues/2

I wouldn't want that to be disabled by default when it's implemented though.

**Comment by Simn** [comment]
> I wouldn't want that to be disabled by default when it's implemented though.

I would, that feature is obnoxious...

**Comment by Gama11** [comment]
Moved to https://github.com/vshaxe/vshaxe/issues/97.
