### ISSUE TITLE
Disable unused import warnings for haxelibs by default

### ISSUE THREAD

**Issue by Gama11** [vshaxe/haxe-languageserver#15]
Not good for libs like Nape:

![](http://i.imgur.com/wLYjbW1.png)

Would be nice if they could still be enabled on request though via some config flag, if you're the one developing the lib.

**Comment by Simn** [comment]
Doesn't it only report this for open files anyway?

**Comment by Gama11** [comment]
I might have been in a Nape file briefly via Go To Definition, but they warnings definitely didn't go away after that.

**Comment by nadako** [comment]
I'll look into this, maybe it's extension's job to clear diagnostics for closed documents.

**Comment by Simn** [comment]
Well, you don't want to clear anything if you do some sort of global diagnostics run, assuming that's a thing. But I also noticed errors/warnings sticking around too long, not sure how to approach this.

**Comment by Gama11** [comment]
I guess this is covered by `"haxe.diagnosticsPathFilter"` now, which is limited to the workspace by default.
