### ISSUE TITLE
Invalid signature position while typing property declaration

### ISSUE THREAD

**Issue by Gama11** [vshaxe/haxe-languageserver#16]
I got this while typing the starting `(` of a property declaration:

```haxe
[Error - 20:35:47] Request textDocument/signatureHelp failed.
  Message: Invalid signature position {
    line : 67, 
    character : 25
}
  Code: 0 
```

Unfortunately I don't have a repro case that reproduces this reliably right now.

**Comment by Simn** [comment]
Can you try if the new signature handling fixes this?

**Comment by Gama11** [comment]
Let's call this fixed, I didn't have a way to consistently repro this anyway.
