### ISSUE TITLE
Invalid positions reported by diagnostics when file is not ascii-only

### ISSUE THREAD

**Issue by nadako** [vshaxe/haxe-languageserver#17]
This is due to 3468d0286da05fb77970ca625e138229bcd656a0. and until https://github.com/HaxeFoundation/haxe/issues/5163 is implemented, we're gonna need to open each file and do these conversions.

**Comment by Gama11** [comment]
Is that really practical? What happens when you try to open each file in FlixelCoverageTests, with Lime, OpenFL, Flixel, Nape and Hscript - I'd imagine that would take a while?

**Comment by nadako** [comment]
It's really not practical, but if there won't be an ugly workaround, everyone will continue ignoring the issue.

**Comment by nadako** [comment]
just to illustrate the issue:
![](http://i.imgur.com/Z3kKPHc.png)

**Comment by Gama11** [comment]
Moved to https://github.com/vshaxe/vshaxe/issues/98.
