### ISSUE TITLE
Support for anonymous structure member completion

### ISSUE THREAD

**Issue by RSDuck** [vshaxe/haxe-languageserver#21]
E.g. snow, or luxe heavily use structures to pass arguments to functions. They recommend their own [Atom](https://github.com/snowkit/atom-haxe) or [Sublime Edit Plugin](https://github.com/snowkit/sublime_haxe), which has the capabilities to autosuggest the struct members.

Here is an example of what I mean:
```haxe
enum Operator {
    Plus
    Minus
    Times
    Through
}
typedef Operation = {
    left:Int,
    right:Int,
    op:Operator
}
//...
static function calc(op:Operation):Int {
        return switch(op.op) {
            case Plus: op.left + op.right;
            case Minus: op.left - op.right;
            case Times: op.left * op.right;
            case Through: cast(op.left / op.right);
        };
    }
//...
calc({}); //Their Atom plugin suggest within the curly brackets left, right and op
//...
```
This really annoys me, because otherwise this extension is amazing!

**Comment by nadako** [comment]
This apparently was implemented in Haxe (see https://github.com/HaxeFoundation/haxe/issues/3907), but also never tested properly and/or supported in haxe language server.
