### ISSUE TITLE
Type suggestion gets aborted after typing space

### ISSUE THREAD

**Issue by RSDuck** [vshaxe/haxe-languageserver#22]
When I want to write a function signature I prefer to put a space after the colon. But this cancels the suggestion completely and it isn't possible to get it back.

![gif4](https://cloud.githubusercontent.com/assets/9352526/19489087/0470614c-956a-11e6-940f-c254535bf408.gif)

**Comment by nadako** [comment]
@Simn is this something we should handle in the language server or in haxe itself?

**Comment by Simn** [comment]
I'd say that's vshaxe's job. We _could_ potentially support this in Haxe, but there's no point in sending a second request anyway.

**Comment by nadako** [comment]
I'm not sure we can easily avoid sending the second request without some ugly caching, but we at least could skip leading spaces when calculating completion position so it works if you invoke completion after the space.

Ideally, the completion shouldn't be canceled at all, but I'm pretty sure that has something to do with VS Code itself and how it handles words. @Gama11 researched something regarding that. Maybe he can say something about it? Otherwise we should contact Microsoft :)

**Comment by Gama11** [comment]
>I'm not sure we can easily avoid sending the second request

I'm not even sure we _can_ send a second request. For that to happen, we would have to add space as a trigger character for completion (if that's even allowed), and that definitely doesn't sound like a good idea... So really, we'd have to make sure completion isn't canceled to begin with.

VSCode cancels completion on non-word characters, (see https://github.com/Microsoft/vscode/issues/12772#issuecomment-250100866).

Right now we adjust the word pattern for meta completion: https://github.com/vshaxe/vshaxe/blob/ae44668c450a423346e95de2be91a7d95753b4de/src/vshaxe/Main.hx#L26-L28

So in theory, matching `(: )` as a word (and who knows what else wordPattern is used for, so this might have unwanted side-effects) as well should keep completion open. But even with that, space still cancels completion.

**Comment by nadako** [comment]
Actually what we should do is look at how MS deals with that in TypeScript extension, because IIRC "spaces after colon" is the preferred code style there.

**Comment by Gama11** [comment]
I actually checked that earlier - it looks like they don't, completion doesn't trigger after `:`.

**Comment by nadako** [comment]
Right, and even if I trigger it manually, it returns simple toplevel completion, not type completion... Anyway we should discuss some ways to implement it correctly with language protocol people. For the time being I propose scanning back to `:` skipping spaces so we can at least manually invoke type completion after space.

**Comment by Gama11** [comment]
This now works with an arbitrary amount of whitespace after `:`.

**Comment by Gama11** [comment]
Moved to https://github.com/vshaxe/vshaxe/issues/99.
