### ISSUE TITLE
[Feature] Show macro-times as diagnostics

### ISSUE THREAD

**Issue by fzzr-** [vshaxe/haxe-languageserver#25]
I think we should show results from `-D macro-times` as part of CodeLens hint to the macro-functions (nearby references and implementers hints). Personally I need it very much some times.

I mean something like that but with better wording:

![screen shot 2016-12-06 at 02 28 46](https://cloud.githubusercontent.com/assets/888526/20906942/def7749c-bb5b-11e6-9c4d-48d4e90084cd.png)

**Comment by Gama11** [comment]
Since this will have to be handled on the Haxe side, I'm moving the issue there: https://github.com/HaxeFoundation/haxe/issues/5990
