### ISSUE TITLE
Restart the haxe display server is request is taking too long.

### ISSUE THREAD

**Issue by nadako** [vshaxe/haxe-languageserver#29]
Subj. See https://github.com/HaxeFoundation/haxe/issues/6005

**Comment by Gama11** [comment]
Not sure if we can reasonably detect that - in large projects, it can take quite long for requests to return, especially if the completion cache is disabled.

It might be good to only warn the user with an info message "Server is taking longer than expected to respond, restart it?" and then offer Yes/No options.

**Comment by nadako** [comment]
I like that!

**Comment by nadako** [comment]
(and a configurable timeout)

**Comment by Gama11** [comment]
So, should we still disable struct completion for now if this is implemented?

**Comment by nadako** [comment]
I don't know, it depends on how often this is actually happening.

**Comment by Gama11** [comment]
Moved to https://github.com/vshaxe/vshaxe/issues/100.
