### ISSUE TITLE
find references

### ISSUE THREAD

**Issue by nadako** [vshaxe/haxe-languageserver#5]
I'd like to have this working properly (i.e. not only in current file).

@Simn how it should be done wrt haxe? should languageserver maintain the list of `.hx` files in the project, be aware of classpaths and convert those files to qualified module paths and pass them to haxe compiler?

**Comment by Simn** [comment]
I was thinking to utilize `--macro include` somehow but you easily run the risk of including stuff that is not meant to be used on the current target. I'm inclined to think that usage completion really requires a normal build step through the compilation server first.

**Comment by Gama11** [comment]
Moved to https://github.com/vshaxe/vshaxe/issues/96.
